#!/bin/bash

export MEDIT_TIMEOUT=10
export MEDIT_MAXUSERS=3
export MEDIT_MAXLINES=15
export MEDIT_MAXCOLUMNS=45
export MEDIT_FICHEIRO="fich_db/medit.db"
export MEDIT_NUM_PIPES=2
export MEDIT_NAME_PIPE_PRINCI="pipe_princi"
